### ISSUE TITLE
Submodule updates don't work?

### ISSUE THREAD

**Issue by shunshou** [ucb-art/dsp-template#1]
Git issue with BWRC servers?

**Comment by shunshou** [comment]
Issue resolved with new Git version. >=1.9.1 works.

**Comment by grebe** [comment]
Readme should mention this with a suggestion of where to grab git (do we recommend installing git from source? adding Palmer's git to your path?)

**Comment by shunshou** [comment]
Palmer's git is specific to our servers? So some more generic steps should be ideal?
