### ISSUE TITLE
Multiple personality disorder

### ISSUE THREAD

**Issue by ducky64** [ucb-art/dsp-template#7]
Is this supposed to be the template for a DSP block (library) or a top-level chip? Because it looks like both.

If a DSP block library: then refactor out the stuff needed for a top-level chip (Top.scala, Generator.scala). That's the responsibility of the system integrator, not the person designing the DSP block (and that person probably doesn't want to deal with all the top-level parameters that's essentially noise and unnecessarily complicates things). In fact, you probably don't want a different copy of the same top-level design for every DSP block.

If a top-level chip: then we need a template for a DSP block library.

**Comment by shunshou** [comment]
I think I've already posted an issue about this in dsp-framework ~a month ago. Theoretically, it should be for a DSP block, but b/c any kind of system with rocket-chip is just a PITA w/o rocket-chip kind of already included, I think Stevo + Paul decided they'd just have this. If anything, you should be using my Chisel3DspExample repo for a Dsp only thing (b/c yea, who wants all that overhead when you're just prototyping a DspBlock?).
